In [10]:
#dependencies
import pandas as pd
import csv

In [11]:
# File to Load
file_to_load = "C:/Users/joely/Desktop/Tableau-Challenge/Resources_Cleaned/data_19.csv"

# Read Purchasing File and store into Pandas data frame
df_2019 = pd.read_csv(file_to_load)

# Observe the result
df_2019.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,month
0,689,00:04.3,11:33.8,3359,E 68 St & Madison Ave,40.769157,-73.967035,164,E 47 St & 2 Ave,40.753231,-73.970325,35033,Subscriber,1989,Jan-19
1,204,00:05.5,03:30.5,3504,E 123 St & Lexington Ave,40.802926,-73.937900,3490,E 116 St & 2 Ave,40.796879,-73.937261,20501,Subscriber,1966,Jan-19
2,316,00:10.2,05:27.2,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,243,Fulton St & Rockwell Pl,40.688226,-73.979382,18386,Subscriber,1984,Jan-19
3,726,00:22.0,12:28.2,495,W 47 St & 10 Ave,40.762699,-73.993012,3660,W 16 St & 8 Ave,40.741022,-74.001385,27616,Subscriber,1983,Jan-19
4,397,00:29.6,07:07.4,473,Rivington St & Chrystie St,40.721101,-73.991925,3467,W Broadway & Spring Street,40.724947,-74.001659,35096,Subscriber,1976,Jan-19

In [12]:
# File to Load
file_to_load = "C:/Users/joely/Desktop/Tableau-Challenge/Resources_Cleaned/data_20.csv"

# Read Purchasing File and store into Pandas data frame
df_2020 = pd.read_csv(file_to_load)

# Observe the result
df_2020.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,month
0,789,00:55.4,14:05.1,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,Jan-20
1,1541,01:08.1,26:49.2,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,Jan-20
2,1464,01:42.1,26:07.0,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,Jan-20
3,592,01:45.6,11:38.2,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,Jan-20
4,702,01:45.8,13:28.2,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,Jan-20

In [13]:
#merge 2019 and 2020
merged = pd.concat([df_2019,df_2020],ignore_index=True)
merged

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,month
0,689,00:04.3,11:33.8,3359,E 68 St & Madison Ave,40.769157,-73.967035,164,E 47 St & 2 Ave,40.753231,-73.970325,35033,Subscriber,1989,Jan-19
1,204,00:05.5,03:30.5,3504,E 123 St & Lexington Ave,40.802926,-73.937900,3490,E 116 St & 2 Ave,40.796879,-73.937261,20501,Subscriber,1966,Jan-19
2,316,00:10.2,05:27.2,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,243,Fulton St & Rockwell Pl,40.688226,-73.979382,18386,Subscriber,1984,Jan-19
3,726,00:22.0,12:28.2,495,W 47 St & 10 Ave,40.762699,-73.993012,3660,W 16 St & 8 Ave,40.741022,-74.001385,27616,Subscriber,1983,Jan-19
4,397,00:29.6,07:07.4,473,Rivington St & Chrystie St,40.721101,-73.991925,3467,W Broadway & Spring Street,40.724947,-74.001659,35096,Subscriber,1976,Jan-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59210,1508,40:02.8,05:11.1,3323,W 106 St & Central Park West,40.798186,-73.960591,2006,Central Park S & 6 Ave,40.765909,-73.976342,32203,Customer,1978,Feb-20
59211,578,40:05.4,49:44.4,251,Mott St & Prince St,40.723180,-73.994800,223,W 13 St & 7 Ave,40.737815,-73.999947,21234,Subscriber,1984,Feb-20
59212,381,40:05.5,46:26.8,458,11 Ave & W 27 St,40.751396,-74.005226,3686,Gansevoort St & Hudson St,40.739448,-74.005070,31208,Subscriber,1963,Feb-20
59213,92,40:11.8,41:44.5,3125,45 Rd & 11 St,40.747086,-73.949772,3121,Jackson Ave & 46 Rd,40.745248,-73.947333,20815,Subscriber,1988,Feb-20
59214,3718,40:13.9,42:12.2,3363,E 102 St & Park Ave,40.790483,-73.950331,3292,5 Ave & E 93 St,40.785785,-73.957481,19870,Customer,1969,Feb-20

In [14]:
#save merged data as new csv
merged.to_csv('Resources_Cleaned/merged_data.csv', index=False)