In [19]:
#dependencies
import pandas as pd
import csv

# Jan 2020

In [20]:


# Read Purchasing File and store into Pandas data frame
Jan_df = pd.read_csv("C:/Users/joely/Desktop/Tableau-Challenge/Resources/2020/Jan-2020.csv")

In [21]:
Jan_df = pd.read_csv(file_to_load)
# Using 'month' as the column name

Jan_df["month"] = "January 2020"
Jan_df.to_csv("file_to_load", index=False)

 
# Observe the result
Jan_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,month
0,789,00:55.4,14:05.1,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,January 2020
1,1541,01:08.1,26:49.2,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,January 2020
2,1464,01:42.1,26:07.0,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,January 2020
3,592,01:45.6,11:38.2,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,January 2020
4,702,01:45.8,13:28.2,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,January 2020

# Feb 2020

In [22]:
 
# File to Load
file_to_load = "C:/Users/joely/Desktop/Tableau-Challenge/Resources/2020/Feb-2020.csv"

# Read Purchasing File and store into Pandas data frame
Feb_df = pd.read_csv(file_to_load)

# Using 'month' as the column name

Feb_df["month"] = "February 2020"
Feb_df.to_csv("file_to_load", index=False)

 
# Observe the result
Feb_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,month
0,789,00:55.4,14:05.1,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,February 2020
1,1541,01:08.1,26:49.2,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,February 2020
2,1464,01:42.1,26:07.0,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,February 2020
3,592,01:45.6,11:38.2,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,February 2020
4,702,01:45.8,13:28.2,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,February 2020

# Merge 2020 Data

In [23]:
#Merge all 2020 data
Data_Merge = pd.concat([Jan_df, Feb_df], ignore_index=True)

In [24]:
# Create csv
Data_Merge.to_csv('Resources_Cleaned/data_20.csv', index=False)